// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

/// @notice Minimal Groth16 verifier interface as generated by snarkjs.
/// @dev Different circuits will have different `input` lengths.
interface IGroth16Verifier {
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[2] calldata input
    ) external view returns (bool);
}

